######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 21 14:51:24 2014
######################################################################

TEMPLATE = app
TARGET = picsorganiser
DEPENDPATH += . ui
INCLUDEPATH += .

# Input
HEADERS += mainWindow.h
FORMS += ui/mainWindow.ui
SOURCES += main.cpp mainWindow.cpp
