# This workflow will install Python dependencies, run tests and lint
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Package, lint and test

on: [pull_request]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  report-coverage:
    runs-on: ubuntu-latest
    # permissions: write-all
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Test with pytest
      run: |
        pytest --cov=src --junitxml=pytest.xml --cov-report="xml:coverage.xml" | tee pytest-coverage.txt
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        pytest-xml-coverage-path: ./coverage.xml
        junitxml-path: ./pytest.xml
        title: Full Coverage
        badge-title: Code Coverage
        junitxml-title: JUnit XML Summray
        hide-badge: false
        hide-report: false
        create-new-comment: false
        hide-comment: false
        report-only-changed-files: false
        remove-link-from-badge: false
